version: '3.8'

x-gluetun-common: &gluetun-template
  image: qmcgaw/gluetun
  cap_add:
    - NET_ADMIN

services:
  gluetun60001:
    <<: *gluetun-template
    container_name: gluetun60001
    ports:
      - "60001:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Phoenix"

  gluetun60002:
    <<: *gluetun-template
    container_name: gluetun60002
    ports:
      - "60002:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Ashburn"

  gluetun60003:
    <<: *gluetun-template
    container_name: gluetun60003
    ports:
      - "60003:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Atlanta"

  gluetun60004:
    <<: *gluetun-template
    container_name: gluetun60004
    ports:
      - "60004:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "San Francisco"

  gluetun60005:
    <<: *gluetun-template
    container_name: gluetun60005
    ports:
      - "60005:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "San Jose"

  gluetun60006:
    <<: *gluetun-template
    container_name: gluetun60006
    ports:
      - "60006:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Boston"

  gluetun60007:
    <<: *gluetun-template
    container_name: gluetun60007
    ports:
      - "60007:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Buffalo"

  gluetun60008:
    <<: *gluetun-template
    container_name: gluetun60008
    ports:
      - "60008:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Charlotte"

  gluetun60009:
    <<: *gluetun-template
    container_name: gluetun60009
    ports:
      - "60009:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Chicago"

  gluetun60010:
    <<: *gluetun-template
    container_name: gluetun60010
    ports:
      - "60010:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Dallas"

  gluetun60011:
    <<: *gluetun-template
    container_name: gluetun60011
    ports:
      - "60011:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Denver"

  gluetun60012:
    <<: *gluetun-template
    container_name: gluetun60012
    ports:
      - "60012:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Detroit"

  gluetun60013:
    <<: *gluetun-template
    container_name: gluetun60013
    ports:
      - "60013:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Bend"

  gluetun60014:
    <<: *gluetun-template
    container_name: gluetun60014
    ports:
      - "60014:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Kansas City"

  gluetun60015:
    <<: *gluetun-template
    container_name: gluetun60015
    ports:
      - "60015:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Seattle"

  gluetun60016:
    <<: *gluetun-template
    container_name: gluetun60016
    ports:
      - "60016:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Latham"

  gluetun60017:
    <<: *gluetun-template
    container_name: gluetun60017
    ports:
      - "60017:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Los Angeles"

  gluetun60018:
    <<: *gluetun-template
    container_name: gluetun60018
    ports:
      - "60018:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Miami"

  gluetun60019:
    <<: *gluetun-template
    container_name: gluetun60019
    ports:
      - "60019:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "New York"

  gluetun60020:
    <<: *gluetun-template
    container_name: gluetun60020
    ports:
      - "60020:8888"
    environment:
      HTTPPROXY: "on"
      HTTPPROXY_PORT: "8888"
      VPN_SERVICE_PROVIDER: "surfshark"
      VPN_TYPE: "wireguard"
      WIREGUARD_PRIVATE_KEY: "${surfshark_PRIVATE_KEY}"
      WIREGUARD_ADDRESSES: "10.14.0.2/16"
      SERVER_CITIES: "Salt Lake City"
